<?php

/**
 * File for the CiviCRM APIv3 API wrapper
 *
 * @package CiviCRM_APIv3
 * @subpackage API
 *
 * @copyright CiviCRM LLC (c) 2004-2010
 * @version $Id: api.php 30486 2010-11-02 16:12:09Z shot $
 */

/*
 * 
usage
$result = civicrm_api('civicrm_contact_get', 'Contact', $params);
@TODO the class is generated by our code. TO be verified

*/

/*
 * @param string $function name of API function
 * @param string $class name of file
 * @param array $params array to be passed to function
 */


function civicrm_api($function, $class, $params){
  require_once 'CRM/Utils/String.php';
  $version = 3;
  if (defined('CIVICRM_API_VERSION')) {
    $version = CIVICRM_API_VERSION;
  }
  if (!empty($params['version'])){
    $version = (int)  $params['version'];
  }
  // clean up. they should be alphanumeric and _ only
  $class = CRM_Utils_String::munge( $class );
  $function = CRM_Utils_String::munge( $function );

  require_once 'civicrm/api/v' . $version . '/' . $class .'.php';
  $function($params);
}



